### ISSUE TITLE
A little questuon about ENAS

### ISSUE THREAD

**Issue by ChaliceCooper** [negrinho/deep_architect#4]
hi,i'm new in your project,and it is the first time i ask question on github,Please bear with me if there are any mistakes. I find something may be wrong in your code about ENAS.
when i finish a code about ENAS by imitating your "main_tensorflow.py"  and i run it and find some error.

Traceback (most recent call last):

File "C:/Users/JssI/Desktop/deep_architect-masterPZJ/ENAS.py", line 322, in <module> main()

File "C:/Users/JssI/Desktop/deep_architect-masterPZJ/ENAS.py", line 312, in main inputs, outputs, _ ,searcher_eval_token = searcher.sample()

File "C:\Users\JssI\Desktop\deep_architect-masterPZJ\dev\enas\searcher\enas_searcher.py", line 104, in sample  outputs, list(hs.values()))):
NameError: name 'hs' is not defined

so i click into the "enas_searcher.py" i find that there is one  variable is not declared which named "hs"

`

     def sample(self):
        arc = self._sample()
        idx = 0
        hyp_values = {}
        for i in range(1, self.num_layers + 1):
            hyp_values['op_' + str(i)] = arc[idx]
            idx += 1
            for j in range(i - 1):
                hyp_values['H.skip_' + str(j) + '_' + str(i) + '-0'] = arc[idx]
                idx += 1

        inputs, outputs = self.search_space_fn()
        vs = []
        for i, h in enumerate(
                unassigned_independent_hyperparameter_iterator(
                    outputs, list(hs.values()))):
            if h.get_name() in hyp_values:
                v = h.vs[hyp_values[h.get_name()]]
                h.assign_value(v)
                vs.append(v)
            else:
                v = random_specify_hyperparameter(h)
                vs.append(v)
        return inputs, outputs, vs, {'arc': arc}
`

What you do is a really nice work  and  i want to use your code to finish my experiment  during my holiday, i will very very appreciate you if you could help me solve the problem. Thank u!

**Comment by ChaliceCooper** [comment]
by the way ,  could u write a code to call the enas as a simple example ? Thank u!!!!

**Comment by negrinho** [comment]
I can eventually look at this, as we want to have ENAS implemented. Unfortunately, the code in the `dev` folder is highly experimental. It is kept there mostly as a reference for when we get around making it part of the main folder. Currently, I can only provide guidance on how to implement ENAS in the current codebase (e.g., where to look to support the operations needed for ENAS). With my current availability, it will be one or two weeks until I can look at this myself (and I'm not making any hard promises right now). 

That being said, if you decide to implement ENAS yourself in DeepArchitect, I can provide support.
